apiVersion: v1
kind: Service
metadata:
  name: watermark-detection-in-images-service
spec:
  selector:
    app: watermark-detection-in-images-app
  ports:
    - protocol: TCP
      port: 80              # External t
      targetPort: 8000       # The port inside the container where FastAPI is running
  type: LoadBalancer         # Use LoadBalancer for external access, or NodePort for local testing
